baseURL = "https://blog.sigaltstack.com"
#title   = "ğ™½Ì¶ğš˜Ì¶ğšÌ¶ ğ™½Ì¶ğšÌ¶ğšŒÌ¶ğšÌ¶ğšœÌ¶ğšœÌ¶ğšŠÌ¶ğš›Ì¶ğš’Ì¶ğš•Ì¶ğš¢Ì¶ ğ™¿Ì¶ğš›Ì¶ğšŠÌ¶ğšŒÌ¶ğšÌ¶ğš’Ì¶ğšŒÌ¶ğšŠÌ¶ğš•Ì¶"
title   = "ê¤ê‹â±¦ ê¤Ä“È¼Ä“ê©ê©â±¥ÉÄ«Å‚É êÉâ±¥È¼â±¦Ä«È¼â±¥Å‚"
languageCode = "en-us"
theme="archie"
copyright = "Â© vilroi"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="auto"
	useCDN=false
	subtitle = "vilroi's blog"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vilroi"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    url        = "/notes"

  [[menu.main]]
    identifier = "links"
    name       = "Links"
    url        = "/links"

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags"
